name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Generate Snake Game from Contributions
        uses: Platane/snk@v3
        with:
          github_user_name: lakipop
          outputs: |
            ./assets/github-contribution-grid-snake.svg
            ./assets/github-contribution-grid-snake.gif
          color_snake: "#ff007f"
          color_dots: "#ffeb3b,#b2ff59,#4caf50,#087f23,#087f23"

      - name: Commit and Push Snake Game files
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add assets/
          git commit -m "Generate snake game from contributions" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git push origin HEAD:main
